services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.36.9
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=https,crypto
      - GRAPH_CLIENT_ID=${GRAPH_CLIENT_ID}
      - GRAPH_CLIENT_SECRET=${GRAPH_CLIENT_SECRET}
      - GRAPH_TENANT_ID=${GRAPH_TENANT_ID}
      - GRAPH_SITE_ID=${GRAPH_SITE_ID}
      - GRAPH_DRIVE_ID=${GRAPH_DRIVE_ID}
      - GRAPH_ITEM_ID=${GRAPH_ITEM_ID}
      - NETLIFY_SITE_ID=${NETLIFY_SITE_ID}
      - NETLIFY_TOKEN=${NETLIFY_TOKEN}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    external: true
